API:
  - FunctionName: 摸鱼日历
    SourceUrl: https://gitee.com/velor2012/mahou/raw/output/output.png
    isAutoPush: true
    PushTime: 0 44 * * * ?
    PushGroupList: []
  - FunctionName: 今日新闻
    SourceUrl: https://api.03c3.cn/api/zb
    isAutoPush: true
    PushTime: 0 44 * * * ?
    PushGroupList: []
  - FunctionName: 真寻日报
    SourceUrl: https://api.atxrom.cn/
    isAutoPush: true
    PushTime: 0 44 * * * ?
    PushGroupList: []
