API:
  - FunctionName: 摸鱼日历
    SourceUrl: https://gitee.com/velor2012/mahou/raw/output/output.png
  - FunctionName: 今日新闻
    SourceUrl: https://api.03c3.cn/api/zb
  - FunctionName: 真寻日报
    SourceUrl: https://http://api.atxrom.cn/
