setpush:
  - 功能: 定时发图
    isAutoPush: true
    time: 0 0 */1 * * ?
    groupList:
      - 877538147
      - 877538147
  - 功能: 摸鱼日历
    isAutoPush: false
    time: 0 30 9 * * ?
    groupList:
      - 877538147
  - 功能: 今日新闻
    isAutoPush: false
    time: 0 30 7 * * ?
    groupList: []
  - 功能: 城市天气
    isAutoPush: false
    time: 0 30 8 * * ?
    groupList: []
  - 功能: 今日番剧
    isAutoPush: false
    time: 0 30 18 * * ?
    groupList: []
defaultCity: 北京
