Switch: true
GalleryimageUrls:
  - https://t.mwm.moe/pc
jrysSwitch: true
jrysimageUrls:
  - https://t.mwm.moe/mp
suanguaSwitch: true
suanguaimageUrls:
  - https://t.mwm.moe/mp
weatherSwitch: true
weatherimageUrls:
  - https://t.mwm.moe/mp
signSwitch: true
signimageUrls:
  - https://t.mwm.moe/pc
