setimage:
  - 功能: default
    imageUrls:
      - C:/Users/logie/Pictures
  - 功能: 今日签到
    imageUrls:
      - https://t.mwm.moe/pc
      - https://www.dmoe.cc/random.php
      - https://t.mwm.moe/ys
      - https://t.mwm.moe/fj
      - https://api.vvhan.com/api/girl
      - https://api.asxe.vip/scenery.php
      - https://api.horosama.com/random.php
      - https://api.likepoems.com/img/pc/
